In [1]:
"""
1.Introduction 
This assignment will help you to consolidate the concepts learnt in the session. 
2.Problem Statement 


Note: Solution submitted via github must contain all the detailed steps. 
3.Output 
This assignment consists of 200 marks and needs to be submitted in the upcoming session for evaluation. 
"""

'\n1.Introduction \nThis assignment will help you to consolidate the concepts learnt in the session. \n2.Problem Statement \n\n\nNote: Solution submitted via github must contain all the detailed steps. \n3.Output \nThis assignment consists of 200 marks and needs to be submitted in the upcoming session for evaluation. \n'

In [2]:
"""Problem Statement 1: 
Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument.
Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde. """

'Problem Statement 1: \nWrite a function so that the columns of the output matrix are powers of the input vector. \nThe order of the powers is determined by the increasing boolean argument.\nSpecifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. \nHINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde. '

In [4]:
import numpy as np
def fun_vandermonde(vec,x):
    try:
        mat=np.ones((len(vec),x))
        for i in range(0,len(vec)):
            #print("i:",i)
            count=x-1
            for j in range(0,x):
                #print("j:",j)
                mat[i][j]=(vec[i]**(count))
                count=count-1
        return mat
    except Exception as e:
        print(e)

In [6]:
arr=np.array([1,2,3,4])
zz=fun_vandermonde(arr,4)
zz

array([[ 1.,  1.,  1.,  1.],
       [ 8.,  4.,  2.,  1.],
       [27.,  9.,  3.,  1.],
       [64., 16.,  4.,  1.]])

In [7]:
"""Problem Statement 2: 
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: 
The moving average sequence has n-k+1 elements as shown below. 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
i 1 2 3 4 5 6 7 8 9 10 ===== == == == == == == == == == == Input 10 20 30 40 50 60 70 80 90 100 y1 25 = (10+20+30+40)/4 y2 35 = (20+30+40+50)/4 y3 45 = (30+40+50+60)/4 y4 55 = (40+50+60+70)/4 y5 65 = (50+60+70+80)/4 y6 75 = (60+70+80+90)/4 y7 85 = (70+80+90+100)/4 
Thus, the moving average sequence has n-k+1=10-4+1=7 values. """

'Problem Statement 2: \nGiven a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: \nThe moving average sequence has n-k+1 elements as shown below. \nThe moving averages with k=4 of a ten-value sequence (n=10) is shown below \ni 1 2 3 4 5 6 7 8 9 10 ===== == == == == == == == == == == Input 10 20 30 40 50 60 70 80 90 100 y1 25 = (10+20+30+40)/4 y2 35 = (20+30+40+50)/4 y3 45 = (30+40+50+60)/4 y4 55 = (40+50+60+70)/4 y5 65 = (50+60+70+80)/4 y6 75 = (60+70+80+90)/4 y7 85 = (70+80+90+100)/4 \nThus, the moving average sequence has n-k+1=10-4+1=7 values. '

In [8]:
import numpy as np
def fun_MAseq(arr,n):   #Taking array and n
    cumsum=np.cumsum(np.insert(arr,0,0))  ##Finding a cumulative sum as we will be needing them to calculate numerator
    print(cumsum[n:])
    print(cumsum[:-n])
    return (cumsum[n:] - cumsum[:-n]) / float(n)  ##substracting cumsum from n step ahead value(ex (10+20+30+40-0)/4 and so on)

In [9]:
input=np.array([10,20,30,40,50,60,70,80,90,100])
k=4
y=fun_MAseq(input,k)
y

[100 150 210 280 360 450 550]
[  0  10  30  60 100 150 210]


array([25., 35., 45., 55., 65., 75., 85.])

In [10]:
#Question: Write a function to find moving average in an array over a window: 
#Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [13]:
import numpy as np
def fun_MA(arr,n):
    cumsum=np.cumsum(np.insert(arr,0,0))
    return (cumsum[n:] - cumsum[:-n]) / float(n)

In [14]:
arr1=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
x=fun_MA(arr1,3)
x

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])